### ISSUE TITLE
❄️ Transición de colores en WebGL

### ISSUE THREAD

**Issue by anattolia** [enflujo/imagina-inclusion-migrantes#12]
¿Cómo hacer una transición de colores entre dos puntos en WebGL?

**Comment by 1cgonza** [comment]
Esto parece tener bloqueado este proyecto, podemos dejar esta idea para otra oportunidad y prefiero que avancen con lo que hay, es decir, pulir el heatmap para que indique lo que tiene que indicar de la mejor manera que el heatmap permita.
