### ISSUE TITLE
🎨 sistema de colores

### ISSUE THREAD

**Issue by Juliansintilde** [enflujo/imagina-inclusion-migrantes#13]
Pruebas de paleta de color.
Como no sabemos para qué son, las dejo ahí por ahora

---
Divergente:
![diveregente](https://github.com/enflujo/imagina-inclusion-migrantes/assets/42554838/45f647e8-8bf4-4fa0-bb1c-521d8bf0486b)

---
Linear:
![linear](https://github.com/enflujo/imagina-inclusion-migrantes/assets/42554838/12932d68-bdcd-40cf-98e8-391b79a16dca)

**Comment by 1cgonza** [comment]
Probarlo con el heatmap a ver si funciona. 

También se puede probar con la lista / ranking de municipios a ver cómo se comporta la paleta. Si usáramos esto para indicar la posición del ranking en la lista de municipios, como lo podemos mostrar? color de icono que acompaña el nombre (por ejemplo: 🌀 Medellín, 🌀 Bogotá...), color del texto, colombinas...?
