### ISSUE TITLE
🎱 Indicador, porcentaje y bolitas por personas venezolanas

### ISSUE THREAD

**Issue by Juliansintilde** [enflujo/imagina-inclusion-migrantes#14]
<img width="496" alt="image" src="https://github.com/enflujo/imagina-inclusion-migrantes/assets/42554838/6ccd1d78-8d82-4327-a8e8-eee309316284">

¿Podría corresponer el número de puntos a la población venezolana en el lugar (en este caso 3 presonas)? 
Creo que así nos ahorramos un paso comunicativo y es más claro que los puntos se refieren a la población migrante en ese lugar.

¿el índice que indica al final de la graficación (96.15) se refiere al número procersado después de las permutaciones que hacen, verdad? no es un porcentaje de persona regularizadas, ¿cierto? 
creo que tendríamos que explicar cómo son diferentes y por qué se grafica el porcentaje de regularizados y no el índice

**Comment by 1cgonza** [comment]
Para esto deben sentarse @anattolia y @Juliansintilde a coordinar tanto la forma de representar los datos en la simulación como el sistema gráfico que ayuda a representar esos datos en particular. Porfa trabajen esto en conjunto pues aún no se ha determinado del todo la forma como se traducen los datos a esta simulación.

**Comment by Juliansintilde** [comment]
Yo soy partidario de que las bolas correspondan a la cantidad de personas y las que pasan se corresponan con las afiliadas o las regularizadas (o ambas, si fuera en diferentes regiones en la regulación). Pueda que en esa operación haya que hacer equivalencias según la opblación con los puntos... como hemos hablado un par de veces. Me parece mucho mejor incluso
porque siento que el el índice es muy confuso para hacer la relación de paso de un lado al otro.
