### ISSUE TITLE
🪣 Limpiar ramas

### ISSUE THREAD

**Issue by 1cgonza** [enflujo/imagina-inclusion-migrantes#50]
@Juliansintilde hay varias ramas que parecen muy viejas, porfa borrar las que ya no se están usando y dejar sólo las que se van a integrar eventualmente.

**Comment by Juliansintilde** [comment]
Listo. Borradas todas menos una que se llama `experimiento-cursor`, que aunque no sería para integrar, me gustaría usarla para  hacerles algunas preguntas de Javascript.
