### ISSUE TITLE
🐛 Algunos lugares no se agregan a comparativo

### ISSUE THREAD

**Issue by 1cgonza** [enflujo/imagina-inclusion-migrantes#53]
Por ejemplo San Carlos, Córdoba, pero pasa con otros sobre todo hacia los más inclusivos (verdes). 
Si se agrega el lugar a la simulación, pero no al comparativo y sale este error.

![Captura de pantalla 2024-04-30 124535](https://github.com/enflujo/imagina-inclusion-migrantes/assets/4657617/68b21c8d-97fb-480f-b2ff-4e7ae6020582)

**Comment by anattolia** [comment]
A partir de San Carlos, Córdoba, no se agregan pero aún no sé por qué...

**Comment by 1cgonza** [comment]
> A partir de San Carlos, Córdoba, no se agregan pero aún no sé por qué...

Gracias @anattolia por identificar el punto desde donde se daña, yo tampoco logré ayer 😕. Voy a intentar solucionarlo. Me lo asigno.

**Comment by anattolia** [comment]
Si quieres revisa la rama que subí de comparaciones, quizás mejor integrar eso pero creo que falta una revisadita.

**Comment by 1cgonza** [comment]
Vale, reviso lo que tienes en esa rama y otras cosas que estaba haciendo para arreglarlo y luego integro.
