### ISSUE TITLE
:t-rex: Definir título del proyecto

### ISSUE THREAD

**Issue by 1cgonza** [enflujo/imagina-inclusion-migrantes#68]
Esto creo que lo debemos impulsar nosotros aunque necesitamos ayuda del resto.

**Comment by anattolia** [comment]
Es 'Rompiendo Barreras' o no se ha definido?

**Comment by 1cgonza** [comment]
> Es 'Rompiendo Barreras' o no se ha definido?

Sip, ya quedó.
