### ISSUE TITLE
🌀 sistemas gráficos de prueba

### ISSUE THREAD

**Issue by Juliansintilde** [enflujo/imagina-inclusion-migrantes#9]
Dos sistemas con premisas parecidas: va de lo más denso, largo y enredado a lo cerrrado, completo y armónico.

- En el primer sistema tenemos espirales que se van volviendo más cortas de afuera hacia adentro. Es decir, se le recorta siempre 1/4 de la vuelta (90º) que hace mientras se vuelve más grande para conservar las proporciones. (también podría recortarse los 90º desde adentro).

- En el segundo sistema, el centro de la  espiral se empieza a desaplazar hacia un punto del círuclo. A medida qus ese acerca al borde, pierde giros en la espiral.

----
JPEG de previsaulización:
![_1200escala-espiral](https://github.com/enflujo/imagina-inclusion-migrantes/assets/42554838/6e1e5a05-77bc-4e61-a338-f4f27599a629)
Así están en SVG:
https://uniandes-my.sharepoint.com/:u:/r/personal/j_gonzalezj_uniandes_edu_co/Documents/EnFlujo/Laboratorio%20EnFlujo/Proyectos/2024/ELHRA/Dise%C3%B1o/exportados/espirales/_1200escala-espiral.svg?csf=1&web=1&e=nOtjwU

----
Aquí quedan por separado los elementos en SVG y PNG del comienzo y del final.
Los pasos intermedios los creé con pasos automatizados desde illustrator:
https://uniandes-my.sharepoint.com/:f:/r/personal/j_gonzalezj_uniandes_edu_co/Documents/EnFlujo/Laboratorio%20EnFlujo/Proyectos/2024/ELHRA/Dise%C3%B1o/exportados?csf=1&web=1&e=2pS2sf

---
Y el archivo de Illustrator donde están las pruebas y:
https://uniandes-my.sharepoint.com/:u:/r/personal/j_gonzalezj_uniandes_edu_co/Documents/EnFlujo/Laboratorio%20EnFlujo/Proyectos/2024/ELHRA/Dise%C3%B1o/dise%C3%B1o.ai?csf=1&web=1&e=v9q9QD

**Comment by 1cgonza** [comment]
Ambos pueden funcionar muy bien. @Juliansintilde usted los puede poner a prueba con datos a ver como responden? si necesita ayuda nos dice. 

(@Juliansintilde las imágenes se pueden arrastrar acá en github y quedan incrustadas, porfa mostrarlas directamente y no con enlaces a sharepoint para evitar pasos adicionales de claves.)

**Comment by Juliansintilde** [comment]
Nuevo sistema de diseño. 
Si lo que va a funcionar tanto en la simulación como en el mapa es un sistema de muros, propongo estos íconos para la lista.

Funciona como una cuadrícula de 10x5 (es decir, 50 cuadritos del mismo tamaño). 
Lo que propongo es que se empiece a llenar esa cuadrícula de abajo hacia arriba de forma que vayan haciendo paredes/muros. Si se emieza a dibujar desde abajo en cada columna, no puede haber una casilla llena en la segunda fila, sin que inmediatamente abajo haya otra).

¿Qué tal les parece? @anattolia @1cgonza 
¿Se les ocurre una forma de expresar eso como una función?

A mí lo que no me queda claro en el planteamiento es cómo hacemos para que no tenga que dibujarse toda la fila, para que pueda hacerse una columna al lado de un espacio vacío.

![sistema iconos-100](https://github.com/enflujo/imagina-inclusion-migrantes/assets/42554838/ab235b35-25b2-4e8f-8658-2f743cceb8a8)
